"""
Django settings for hakaSchool project.

Generated by 'django-admin startproject' using Django 3.1.3.


For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%sl78xm=9z-cv*zs#myd_+#i7#tkz=b3l80*fn_8ali2y!yyl6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost','https://mcu-owo.herokuapp.com/','mcu-owo.herokuapp.com',
    'http://mcu-owo.herokuapp.com/' ,'*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main.apps.MainConfig', 
    'pwa',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hakaSchool.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':[os.path.join(BASE_DIR, 'templates').replace('\\', '/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hakaSchool.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# PWA setting
PWA_APP_NAME = 'My App'
PWA_APP_DESCRIPTION = "My app description"
PWA_APP_THEME_COLOR = '#0A0302'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': '/static/img/icons/icon-152x152.png',
        'sizes': '152x152',
        "purpose": "any maskable"
    },
    {
        'src': '/static/img/icons/icon-96x96.png',
        'sizes': '96x96',
        "purpose": "any maskable"
    },
    {
        'src': '/static/img/icons/icon-128x128.png',
        'sizes': '128x128',
        "purpose": "any maskable"
    },
    {
        'src': '/static/img/icons/icon-144x144.png',
        'sizes': '144x144',
        "purpose": "any maskable"
    },
    {
        'src': '/static/img/icons/icon-72x72.png',
        'sizes': '72x72',
        "purpose": "any maskable"
    },
    {
        'src': '/static/img/icons/icon-384x384.png',
        'sizes': '384x384',
        "purpose": "any maskable"
    },
    {
        'src': '/static/img/icons/icon-512x512.png',
        'sizes': '512x512',
        "purpose": "any maskable"
    }
]
PWA_APP_ICONS_APPLE = [
       {
        'src': '/static/img/icons/icon-152x152.png',
        'sizes': '152x152',
        "purpose": "any maskable"
    },
    {
        'src': '/static/img/icons/icon-96x96.png',
        'sizes': '96x96',
        "purpose": "any maskable"
    },
    {
        'src': '/static/img/icons/icon-128x128.png',
        'sizes': '128x128',
        "purpose": "any maskable"
    },
    {
        'src': '/static/img/icons/icon-144x144.png',
        'sizes': '144x144',
        "purpose": "any maskable"
    },
    {
        'src': '/static/img/icons/icon-72x72.png',
        'sizes': '72x72',
        "purpose": "any maskable"
    },
    {
        'src': '/static/img/icons/icon-384x384.png',
        'sizes': '384x384',
        "purpose": "any maskable"
    },
    {
        'src': '/static/img/icons/icon-512x512.png',
        'sizes': '512x512',
        "purpose": "any maskable"
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': '/static/images/icons/splash-640x1136.png',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'static/js', 'serviceworker.js')